name: PHPStan

on:
  workflow_call:
    inputs:
      php:
        default: "8.2"
        type: string
        required: false

jobs:
  phpstan:
    #  skip test for ci commits
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ubuntu-latest
    env:
      extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysqli, bcmath, soap, intl, gd, exif, iconv, imagick, redis

    name: PHPStan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare The Environment
        run: cp .env.example .env

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-composer-${{ hashFiles('composer.json') }}

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ inputs.php }}
          extensions: ${{ env.extensions }}
          key: extension-cache-v1

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: ${{ env.extensions }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
