name: Rector

on:
  workflow_call:
    inputs:
      php:
        default: "8.2"
        type: string
        required: false

jobs:
  rector:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          coverage: none

      - name: Install composer
        uses: "ramsey/composer-install@v2"

      - name: Run Rector
        run: vendor/bin/rector --ansi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ':art: [ci skip] Rector fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'
